[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
security-txt = { workspace = true, features = ["parse"] }

anyhow = { workspace = true }

clap = { version = "4.5.10", features = ["derive"] }
